name: "Execution de pytest pour sonar"
description: "Execution de pytest, avec la normalisation du resultat en xml pour correspondre à ce qu'attend SonarQube"
inputs:
    module:
        description: "Repertoire, ou module ou sera executé le fichier de test"
        required: true
runs:
    using: "composite"
    steps:
    - run: |
        chmod +x ${{ github.action_path }}/script.sh
        ${{ github.action_path }}/script.sh "${{ inputs.module }}"
      shell: bash
