name: PublishR elease

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          security-events: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Qemu
              uses: docker/setup-qemu-action@v3

            - name: Login to Github Container Registery
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                # use the automatically-provided GITHUB_TOKEN (requires permissions: packages: write)
                password: ${{ secrets.GITHUB_TOKEN }}
                
            - name: Convert owner to lowercase
              id: owner
              run: echo "value=${OWNER,,}" >> "$GITHUB_OUTPUT"
              env:
                OWNER: ${{ github.repository_owner }}

            - name: Build en push image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: |
                  ghcr.io/${{ steps.owner.outputs.value }}/ci-labs:latest
                  ghcr.io/${{ steps.owner.outputs.value }}/ci-labs:${{ github.ref_name }}
                annotations: |
                  org.opencontainers.image.description="A test label Anotations"

